login:
  level:
    wer: DEBUG
server:
  port: 8001
spring:
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jpront_db
    username: jpront_user
    password: my@pp_Us3r
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
